spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5434/product_store_db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5434/product_store_db
    user: user
    password: password
    default-schema:
      - product_sc
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
